Repository ICan-5/ICan-Frontend, pull requests merged in 2025-03, with the labels that each got.

#34 [CAN-21/Feat] 대시보드 목표별 할일 UI 개발
  src/app/(member)/page.tsx
  src/components/common/navbar/navGoal/NavGoalItem.tsx
  src/components/common/todo/SimpleTodoSkeleton.tsx
  src/components/dashboard/goalList/GoalList.tsx
  src/components/dashboard/goalList/GoalTab.tsx
  src/components/dashboard/goalList/GoalTabSkeleton.tsx
  src/components/dashboard/todayList/TodayList.tsx
  src/hooks/useDragScroll.ts
Labels: ✨ Feature

#38 [CAN-20/feat] 잔디 UI 개발 & API 연동
  src/app/(member)/page.tsx
  src/components/dashboard/todayProgress/TodayProgress.tsx
  src/components/dashboard/todoGrass/TodoGrass.tsx
  src/components/dashboard/todoGrass/TodoGrassCell.tsx
  src/constants/queryKey.ts
  src/hooks/useDashboard.ts
  src/hooks/useTodos.ts
  src/services/dashboard.ts
  src/styles/globals.css
  src/types/dashboard.d.ts
  src/utils/date.ts
Labels: ✨ Feature, 📬 API

#39 [CAN-47/feat] 오늘의 그래프 실시간 반영, Navbar Logo 수정
  public/images/profile.png
  src/app/(member)/page.tsx
  src/components/common/navbar/Navbar.tsx
  src/components/dashboard/todayProgress/TodayProgress.tsx
  src/hooks/useDashboard.ts
Labels: ✨ Feature, 📬 API, 🌈Style

#30 [CAN-48/feat] 목표 제목 & 할일 생성 api 연동
  pnpm-lock.yaml
  src/app/(member)/goals/[id]/page.tsx
  src/components/goalDetail/GoalBasket.tsx
  src/components/goalDetail/GoalDoneList.tsx
  src/components/goalDetail/GoalHeader.tsx
  src/components/goalDetail/GoalTodoCreateModal.tsx
  src/components/goalDetail/GoalTodoList.tsx
  src/components/goalDetail/GoalTodoModal.tsx
  src/components/note/ConfirmDeleteModal.tsx
  src/components/note/NoteHeader.tsx
  src/components/note/NoteModal.tsx
  src/components/todoCalendar/TodoListItem.tsx
Labels: 📬 API, 🌈Style

#35 [CAN-56/feat] 노트 단일 조회 API 연동
  src/app/(member)/@modal/(.)note/[noteId]/page.tsx
  src/app/(member)/@modal/default.tsx
  src/app/(member)/goals/[id]/note/page.tsx
  src/app/(member)/layout.tsx
  src/app/(member)/note/[noteId]/page.tsx
  src/app/layout.tsx
  src/components/common/button/IconButton.tsx
  src/components/note/NoteItem.tsx
  src/components/note/NoteList.tsx
  src/components/note/NoteModal.tsx
  src/services/note.ts
  src/utils/renderNotePage.tsx
Labels: ✨ Feature, 📬 API, 🌈Style

#29 [CAN-27/feat] 노트 작성하기 ui, 유효성 검사
  package.json
  pnpm-lock.yaml
  src/app/(member)/[todoId]/note/create/page.tsx
  src/app/api/goals/[goalId]/todos/route.ts
  src/components/auth/ErrorMessage.tsx
  src/components/auth/PasswordField.tsx
  src/components/goalDetail/GoalHeader.tsx
  src/components/note/NoteContentEditor.tsx
  src/components/note/NoteEditor.tsx
  src/components/note/NoteTitle.tsx
  src/lib/note-validation.ts
  src/presets/screen.ts
  src/styles/textEditor.css
  src/types/note.d.ts
  tailwind.config.ts
Labels: ✨ Feature, 🌈Style

#37 [CAN-39/feat] 노트 작성하기 API
  src/app/api/goals/[goalId]/route.ts
  src/app/api/note/[todoId]/route.ts
  src/app/api/todos/[todoId]/route.ts
  src/components/note/NoteContentEditor.tsx
  src/components/note/NoteEditor.tsx
  src/components/note/NoteSkeleton.tsx
  src/components/note/NoteTitlesSkeleton.tsx
  src/constants/queryKey.ts
  src/hooks/useTodoWithGoalTitle.ts
  src/lib/note-validation.ts
  src/services/note.ts
Labels: ✨ Feature, 📬 API

#40 [CAN-44/feat] 할 일 목록에서 노트 보기 연결
  package.json
  pnpm-lock.yaml
  src/app/(member)/@modal/(.)note/[noteId]/page.tsx
  src/app/(member)/note/[noteId]/page.tsx
  src/app/api/notes/[noteId]/route.ts
  src/app/api/todos/[todoId]/route.ts
  src/components/note/NoteModal.tsx
  src/components/note/SkeletonNoteModal.tsx
  src/components/todoCalendar/TodoListItem.tsx
  src/constants/queryKey.ts
  src/hooks/useNotes.ts
  src/hooks/useTodos.ts
  src/services/note.ts
  src/types/note.d.ts
  src/utils/renderNotePage.tsx
Labels: ✨ Feature

#36 [CAN-55/feat] 목표별 할 일 리스트 & 장바구니 조회 & 완료 여부 수정
  src/app/(member)/goals/[id]/page.tsx
  src/app/api/goals/[goalId]/todos/[todoId]/route.ts
  src/app/api/goals/[goalId]/todos/route.ts
  src/components/goalDetail/GoalBasket.tsx
  src/components/goalDetail/GoalDoneList.tsx
  src/components/goalDetail/GoalHeader.tsx
  src/components/goalDetail/GoalProgress.tsx
  src/components/goalDetail/GoalTodoCreateModal.tsx
  src/components/goalDetail/GoalTodoList.tsx
  src/components/goalDetail/GoalTodoModal.tsx
  src/components/todoCalendar/TodoListItem.tsx
  src/constants/queryKey.ts
  src/hooks/useGoalsTodo.ts
  src/hooks/useTodos.ts
Labels: ✨ Feature, 📬 API

#41 [CAN-28/feat] 대시보드 목표 탭 useGoalsTodo 연동
  src/components/dashboard/goalList/GoalList.tsx
  src/hooks/useGoalsTodo.ts
Labels: ✨ Feature, 📬 API

#44 [CAN-50/feat] 할 일 장바구니 디자인 추가
  src/app/(member)/layout.tsx
  src/components/common/NavbarContext.tsx
  src/components/common/navbar/Navbar.tsx
  src/components/todoCalendar/CalendarBody.tsx
  src/components/todoCalendar/TodoBasket.tsx
  src/components/todoCalendar/TodoCalendar.tsx
Labels: 🌈Style

#42 [CAN-57/feat] 목표 제목 수정&삭제, 할일 수정&삭제, 노트 연결
  src/app/(member)/goals/[id]/page.tsx
  src/app/api/goals/[goalId]/route.ts
  src/components/goalDetail/GoalDoneList.tsx
  src/components/goalDetail/GoalHeader.tsx
  src/components/goalDetail/GoalTodoCreateModal.tsx
  src/components/goalDetail/GoalTodoList.tsx
  src/components/goalDetail/GoalTodoModal.tsx
  src/hooks/useGoals.ts
  src/hooks/useGoalsTodo.ts
  src/services/goal.ts
  src/services/todo.ts
Labels: ✨ Feature, 📬 API

#46 [CAN-51/feat] 장바구니 api 연동
  src/app/(member)/layout.tsx
  src/app/(member)/todoCalendar/page.tsx
  src/app/api/basket/[id]/route.ts
  src/app/api/basket/route.ts
  src/components/common/MemberPageWrapper.tsx
  src/components/common/navbar/Navbar.tsx
  src/components/todoCalendar/Calendar.tsx
  src/components/todoCalendar/CalendarBody.tsx
  src/components/todoCalendar/TodoBasket.tsx
  src/components/todoCalendar/TodoCalendar.tsx
  src/constants/queryKey.ts
  src/hooks/useTodoBasket.ts
Labels: ✨ Feature, 📬 API

#48 [CAN-63/fix] 회원가입/로그인 코드 및 UI 개선
  package.json
  pnpm-lock.yaml
  src/app/(guest)/(auth)/layout.tsx
  src/app/(guest)/(auth)/loading.tsx
  src/app/(guest)/(auth)/login/page.tsx
  src/app/(guest)/(auth)/signup/page.tsx
  src/app/layout.tsx
  src/components/auth/Button.tsx
  src/components/auth/ErrorMessage.tsx
  src/components/auth/LoginForm.tsx
  src/components/auth/PasswordField.tsx
  src/components/auth/SignupForm.tsx
  src/components/auth/TextField.tsx
  src/components/note/NoteContentEditor.tsx
  src/components/note/NoteEditor.tsx
  src/lib/validation.ts
  src/services/auth.ts
  src/services/note.ts
  src/styles/globals.css
Labels: 🔨 Refactor, 🌈Style

#49 [CAN-58/feat] 노트 페이지 삭제 API 연동
  src/app/(member)/@modal/(.)note/[noteId]/page.tsx
  src/app/(member)/note/[noteId]/edit/page.tsx
  src/app/api/note/[todoId]/route.ts
  src/app/api/notes/[noteId]/route.ts
  src/app/api/notes/route.ts
  src/components/note/NoteModal.tsx
  src/components/note/noteDetail/NoteDetail.tsx
  src/components/note/noteDetail/NoteModal.tsx
  src/components/note/noteDetail/SkeletonNoteModal.tsx
  src/hooks/useNotes.ts
  src/services/note.ts
  src/types/note.d.ts
  src/utils/renderNotePage.tsx
Labels: ✨ Feature, 📬 API

#51 [CAN-64/feat] 목표 상세 페이지 변경된 디자인 적용
  src/app/(member)/goals/[id]/page.tsx
  src/components/goalDetail/BasketCreateTodo.tsx
  src/components/goalDetail/GoalBasket.tsx
  src/components/goalDetail/GoalDoneList.tsx
  src/components/goalDetail/GoalHeader.tsx
  src/components/goalDetail/GoalProgress.tsx
  src/components/goalDetail/GoalTodoList.tsx
  src/components/note/NoteItem.tsx
  src/components/note/NoteList.tsx
  src/presets/colors.ts
  src/presets/goalColors.ts
Labels: 🌈Style

#50 [CAN-60/feat] date picker 디자인 적용
  src/components/common/input/DateInput.tsx
  src/components/common/input/datePicker/CustomDateHeader.tsx
  src/components/common/input/datePicker/CustomDateInput.tsx
  src/components/todoCalendar/CreateTodo.tsx
  src/styles/datePicker.css
Labels: 🌈Style

#53 [CAN-14/feat] 캘린더 페이지 반응형 구현
  src/components/common/ConfirmModal.tsx
  src/components/note/noteDetail/NoteModal.tsx
  src/components/todoCalendar/CreateTodo.tsx
  src/services/note.ts
Labels: 🌈Style

#52 [CAN-40/feat] 노트 작성하기 임시저장, 링크 첨부 기능 구현
  src/components/note/LinkModal.tsx
  src/components/note/NoteContentEditor.tsx
  src/components/note/NoteEditor.tsx
  src/components/note/NoteTitlesSkeleton.tsx
  src/styles/textEditor.css
  src/types/note.d.ts
Labels: ✨ Feature

#57 [CAN-68/fix] 캘린더 페이지 오류 수정
  src/components/todoCalendar/CreateTodo.tsx
  src/components/todoCalendar/TodoCalendar.tsx
  src/components/todoCalendar/TodoList.tsx
Labels: 🐞 BugFix

#45 [CAN-43/feat] 설정 페이지 UI 개발 & 테마 변경
  src/app/(member)/page.tsx
  src/app/(member)/settings/page.tsx
  src/app/layout.tsx
  src/components/common/IcanTitle.tsx
  src/components/common/MemberPageWrapper.tsx
  src/components/common/NonProfile.tsx
  src/components/common/ThemeProvider.tsx
  src/components/common/navbar/Navbar.tsx
  src/components/common/todo/CheckTodo.tsx
  src/components/dashboard/todayList/TodayList.tsx
  src/components/dashboard/todayProgress/TodayProgress.tsx
  src/components/dashboard/todayProgress/TodayProgressError.tsx
  src/components/dashboard/todayProgress/TodayProgressSkeleton.tsx
  src/components/dashboard/todoGrass/TodoGrassCell.tsx
  src/components/settings/FormField.tsx
  src/components/settings/FormTitle.tsx
  src/components/settings/ProfileField.tsx
  src/components/settings/SettingForm.tsx
  src/components/settings/theme/ThemeColors.tsx
  src/components/settings/theme/ThemeTabs.tsx
  src/lib/validation.ts
  src/presets/colors.ts
  src/services/theme.ts
  src/styles/globals.css
Labels: ✨ Feature, 🌈Style

#54 [CAN-65/feat] 목표 색상 수정 반영
  src/app/(member)/goals/[id]/page.tsx
  src/app/api/goals/[goalId]/route.ts
  src/components/goalDetail/GoalBasket.tsx
  src/components/goalDetail/GoalHeader.tsx
  src/components/goalDetail/GoalProgress.tsx
  src/components/goalDetail/GoalTodoList.tsx
  src/hooks/useGoals.ts
  src/hooks/useGoalsTodo.ts
  src/services/goal.ts
Labels: ✨ Feature, 📬 API, 🌈Style

#56 [CAN-67/feat] 장바구니 모두 지우기 & 중복 API 삭제 & 선택한 목표 컬러 테두리 수정
  src/app/(member)/goals/[id]/note/page.tsx
  src/app/(member)/goals/[id]/page.tsx
  src/app/api/baskets/[basketTodoId]/route.ts
  src/app/api/baskets/route.ts
  src/components/goalDetail/GoalBasket.tsx
  src/components/goalDetail/GoalHeader.tsx
  src/hooks/useGoalBasketTodo.ts
  src/services/basket.ts
Labels: ✨ Feature, 📬 API, 🌈Style

#60 [CAN-59/feat] 노트 단일 조회 페이지 링크 임베드 적용
  src/components/note/noteCreate/EmbedPreview.tsx
  src/components/note/noteCreate/LinkModal.tsx
  src/components/note/noteCreate/NoteEditor.tsx
  src/components/note/noteDetail/NoteDetail.tsx
  src/components/note/noteDetail/NoteModal.tsx
  src/utils/renderNotePage.tsx
Labels: ✨ Feature, 🌈Style

#58 [CAN-70/feat] 노트 수정 페이지 기능 구현
  src/app/(member)/note/[noteId]/edit/page.tsx
  src/app/api/notes/[noteId]/route.ts
  src/components/common/ConfirmModal.tsx
  src/components/note/noteCreate/NoteEditor.tsx
  src/components/note/noteDetail/NoteDetail.tsx
  src/components/todoCalendar/CreateTodo.tsx
  src/hooks/useNotes.ts
  src/services/note.ts
Labels: ✨ Feature, 📬 API

#62 [CAN-73/fix] refresh로직 jwt callback함수로 이동
  src/auth.config.ts
  src/auth.ts
  src/services/auth.ts
  src/services/fetchInstance.ts
Labels: 🐞 BugFix, 📬 API

#65 [CAN-72/fix] 로그인 성공 리디렉션 변경, dark 스타일 삭제, 한글 입력 막기 등
  src/app/(guest)/(auth)/layout.tsx
  src/app/(guest)/(auth)/loading.tsx
  src/components/auth/LoginForm.tsx
  src/components/auth/PasswordField.tsx
  src/components/auth/SignupForm.tsx
  src/components/auth/TextField.tsx
Labels: 🐞 BugFix

#68 [CAN-75/fix] 테스트 기반 Navbar 수정
  src/app/(member)/goals/[id]/note/page.tsx
  src/app/(member)/goals/[id]/page.tsx
  src/app/(member)/layout.tsx
  src/components/common/MemberPageWrapper.tsx
  src/components/common/NavbarContext.tsx
  src/components/common/navbar/NavTab.tsx
  src/components/common/navbar/NavUserProfile.tsx
  src/components/common/navbar/Navbar.tsx
  src/components/common/navbar/navGoal/NavGoal.tsx
  src/components/common/navbar/navGoal/NavGoalItem.tsx
  src/hooks/useGoals.ts
  src/types/goals.d.ts
  src/utils/renderNotePage.tsx
Labels: ✨ Feature, 🐞 BugFix, 🌈Style

#64 [CAN-76/fix] 테스트 기반 설정 페이지 수정
  src/components/settings/ProfileField.tsx
  src/components/settings/SettingForm.tsx
  src/styles/globals.css
Labels: ✨ Feature, 🐞 BugFix, 🌈Style

#66 [CAN-80/fix] 노트 조회 페이지 오류 수정
  src/app/api/notes/[noteId]/route.ts
  src/components/common/MemberPageWrapper.tsx
  src/components/note/noteCreate/EmbedPreview.tsx
  src/components/note/noteCreate/NoteEditHeader.tsx
  src/components/note/noteCreate/NoteEditor.tsx
  src/components/note/noteDetail/NoteDetail.tsx
  src/components/note/noteDetail/NoteModal.tsx
  src/constants/queryKey.ts
  src/hooks/useNotes.ts
  src/styles/globals.css
  src/utils/renderNotePage.tsx
  tailwind.config.ts
Labels: 🐞 BugFix

#69 [CAN-78/fix] 노트 생성 페이지 - 목표 색상 적용, 링크 없는 경우 수정 등
  src/app/api/notes/route.ts
  src/components/note/noteCreate/NoteContentEditor.tsx
  src/components/note/noteCreate/NoteEditHeader.tsx
  src/components/note/noteCreate/NoteEditor.tsx
  src/components/note/noteCreate/NoteTitle.tsx
  src/components/note/noteCreate/useTextLength.ts
  src/services/note.ts
  src/styles/textEditor.css
Labels: 🐞 BugFix

#67 [CAN-77/fix] 목표 상세 페이지 테스트 수정
  src/app/(member)/goals/[id]/note/page.tsx
  src/app/(member)/goals/[id]/page.tsx
  src/components/goalDetail/BasketCreateTodo.tsx
  src/components/goalDetail/GoalBasket.tsx
  src/components/goalDetail/GoalDoneList.tsx
  src/components/goalDetail/GoalHeader.tsx
  src/components/goalDetail/GoalTodoCreateModal.tsx
  src/components/goalDetail/GoalTodoList.tsx
  src/components/goalDetail/GoalTodoModal.tsx
  src/hooks/useGoalBasketTodo.ts
  src/presets/goalColors.ts
  src/services/basket.ts
Labels: 🐞 BugFix, 🔨 Refactor

#72 [CAN-81/fix] 다크 모드에 맞는 목표 색상 & 노트 목록 페이지 수정
  src/app/(member)/goals/[id]/page.tsx
  src/components/goalDetail/GoalBasket.tsx
  src/components/goalDetail/GoalHeader.tsx
  src/components/note/NoteItem.tsx
  src/presets/goalColors.ts
Labels: 🐞 BugFix, 🌈Style

#70 [CAN-74/fix] 테스트 기반 대시보드 수정
  src/app/(member)/page.tsx
  src/app/api/todos/[todoId]/route.ts
  src/components/common/ClientProvider.tsx
  src/components/common/todo/SimpleTodo.tsx
  src/components/dashboard/goalList/GoalDoneSection.tsx
  src/components/dashboard/goalList/GoalList.tsx
  src/components/dashboard/goalList/GoalTodoSection.tsx
  src/components/dashboard/todayList/TodayList.tsx
  src/components/dashboard/todayProgress/TodayProgress.tsx
  src/hooks/useDashboard.ts
  src/hooks/useTodos.ts
  src/styles/globals.css
Labels: 🐞 BugFix, 🌈Style

#74 [CAN-84/style] 목표 상세 페이지 디자인 수정
  src/app/(member)/goals/[id]/note/page.tsx
  src/app/(member)/goals/[id]/page.tsx
  src/components/goalDetail/GoalBasket.tsx
  src/components/goalDetail/GoalDoneList.tsx
  src/components/goalDetail/GoalProgress.tsx
  src/components/goalDetail/GoalTodoList.tsx
Labels: 🐞 BugFix, 🌈Style

#73 [CAN-83] fix: 다크모드일 때 텍스트 색 수정, default 목표일 때 색상 가져옴 수정
  src/app/(guest)/(auth)/layout.tsx
  src/components/note/noteCreate/EmbedPreview.tsx
  src/components/note/noteCreate/NoteContentEditor.tsx
  src/components/note/noteCreate/NoteEditHeader.tsx
  src/components/note/noteCreate/NoteEditor.tsx
  src/components/note/noteCreate/NoteTitle.tsx
  src/components/note/noteCreate/NoteTitlesSkeleton.tsx
  src/styles/textEditor.css
Labels: 🐞 BugFix, 🌈Style
