Repository ICan-5/ICan-Frontend, pull requests merged in 2025-02, with the labels that each got.

#5 [CAN-12/feat] 회원가입 UI/반응형
  .eslintrc.json
  package.json
  pnpm-lock.yaml
  src/app/(guest)/signup/page.tsx
  src/app/(member)/page.tsx
  src/components/auth/Button.tsx
  src/components/auth/PasswordField.tsx
  src/components/auth/SignupForm.tsx
  src/components/auth/TextField.tsx
  tailwind.config.ts
Labels: ✨ Feature

#1 [CAN-7/feat] 캘린더 UI 추가
  .eslintrc.json
  package.json
  pnpm-lock.yaml
  src/app/todoCalendar/page.tsx
  src/components/todoCalendar/Calendar.tsx
  src/components/todoCalendar/CalendarHeader.tsx
  src/styles/calendar.css
  tailwind.config.ts
Labels: ✨ Feature

#2 [CAN-17/feat] Navbar 컴포넌트 개발
  .gitignore
  pnpm-lock.yaml
  public/images/profile.png
  src/app/(member)/calendar/page.tsx
  src/app/(member)/goals/[id]/page.tsx
  src/app/(member)/goals/page.tsx
  src/app/(member)/layout.tsx
  src/app/(member)/page.tsx
  src/app/(member)/setting/page.tsx
  src/components/common/navbar/NavProfile.tsx
  src/components/common/navbar/NavTab.tsx
  src/components/common/navbar/NavTabItem.tsx
  src/components/common/navbar/Navbar.tsx
  src/components/common/navbar/navGoal/NavGoal.tsx
  src/components/common/navbar/navGoal/NavGoalItem.tsx
  src/components/common/navbar/navGoal/NewGoalItem.tsx
  src/styles/globals.css
  tailwind.config.ts
Labels: ✨ Feature

#8 [CAN-18/feat] Dashboard 오늘 할일 컴포넌트 구현
  .eslintrc.json
  next.config.mjs
  package.json
  src/app/(member)/layout.tsx
  src/app/(member)/page.tsx
  src/app/(member)/todoCalendar/page.tsx
  src/components/auth/PasswordField.tsx
  src/components/auth/SignupForm.tsx
  src/components/dashboard/todayGraph/TodayGraph.tsx
  src/components/dashboard/todayList/TodayList.tsx
  src/components/dashboard/todayList/TodayListItem.tsx
  src/components/todoCalendar/CalendarHeader.tsx
  src/styles/globals.css
Labels: ✨ Feature

#9 [CAN-9/feat] 선택 날짜 별 할 일 기능 구현
  .eslintrc.json
  .prettierrc
  package.json
  pnpm-lock.yaml
  src/app/(member)/todoCalendar/page.tsx
  src/components/common/Loading.tsx
  src/components/todoCalendar/Calendar.tsx
  src/components/todoCalendar/TodoCalendar.tsx
  src/components/todoCalendar/TodoList.tsx
  src/components/todoCalendar/TodoListItem.tsx
  src/styles/calendar.css
  src/types/todos.d.ts
  tailwind.config.ts
Labels: ✨ Feature

#12 [CAN-11/feat] 할일 장바구니 ui 기능 구현
  src/components/todoCalendar/TodoBasket.tsx
  src/components/todoCalendar/TodoCalendar.tsx
Labels: ✨ Feature

#7 [CAN-30/feat] 목표 상세 페이지 UI & 기능 구현
  package.json
  pnpm-lock.yaml
  src/app/(member)/goals/[id]/page.tsx
  src/components/goalDetail/GoalBasket.tsx
  src/components/goalDetail/GoalDoneList.tsx
  src/components/goalDetail/GoalHeader.tsx
  src/components/goalDetail/GoalListItem.tsx
  src/components/goalDetail/GoalProgress.tsx
  src/components/goalDetail/GoalTodoList.tsx
Labels: ✨ Feature, 🔨 Refactor

#11 [CAN-13/feat] 회원가입 기능 구현
  package.json
  pnpm-lock.yaml
  src/app/(guest)/(auth)/login/page.tsx
  src/app/(guest)/(auth)/signup/page.tsx
  src/app/api/(auth)/signup/route.ts
  src/components/auth/Button.tsx
  src/components/auth/ErrorMessage.tsx
  src/components/auth/PasswordField.tsx
  src/components/auth/SignupForm.tsx
  src/components/auth/TextField.tsx
  src/lib/validation.ts
  src/services/auth.ts
Labels: ✨ Feature, 📬 API

#13 [CAN-33/feat] Navbar 디자인 변경
  package.json
  public/images/profile.png
  src/app/(member)/layout.tsx
  src/components/common/navbar/NavProfile.tsx
  src/components/common/navbar/NavTab.tsx
  src/components/common/navbar/NavTabItem.tsx
  src/components/common/navbar/NavUserProfile.tsx
  src/components/common/navbar/NavUserSetting.tsx
  src/components/common/navbar/Navbar.tsx
  src/components/common/navbar/navGoal/NavGoal.tsx
  src/components/common/navbar/navGoal/NavGoalItem.tsx
  src/components/common/navbar/navGoal/NewGoalItem.tsx
  tailwind.config.ts
Labels: ✨ Feature, 🔨 Refactor

#14 [CAN-31/feat] 장바구니 요소 드래그 드롭 기능 구현
  src/components/todoCalendar/Calendar.tsx
  src/components/todoCalendar/TodoBasket.tsx
  src/components/todoCalendar/TodoCalendar.tsx
  src/components/todoCalendar/TodoListItem.tsx
  src/types/todos.d.ts
Labels: ✨ Feature

#16 [CAN-19/feat] 오늘 할일 그래프 개발
  src/app/(member)/layout.tsx
  src/app/(member)/page.tsx
  src/components/dashboard/todayGraph/TodayGraph.tsx
  src/components/dashboard/todayProgress/TodayGraph.tsx
  src/components/dashboard/todayProgress/TodayProgress.tsx
  src/styles/globals.css
  tailwind.config.ts
Labels: ✨ Feature

#15 [CAN-25/feat] 노트 모아보기 UI 구현
  src/app/(member)/goals/[id]/note/page.tsx
  src/app/(member)/goals/[id]/page.tsx
  src/components/goalDetail/GoalHeader.tsx
  src/components/goalDetail/GoalListItem.tsx
  src/components/note/NoteHeader.tsx
  src/components/note/NoteItem.tsx
  src/components/note/NoteList.tsx
Labels: ✨ Feature

#18 [CAN-15/feat] 할 일 생성 모달 구현
  .eslintrc.json
  package.json
  pnpm-lock.yaml
  public/images/exclude.png
  src/app/(guest)/(auth)/login/page.tsx
  src/components/common/button/Button.tsx
  src/components/common/input/CustomDateInput.tsx
  src/components/common/input/DateInput.tsx
  src/components/common/input/DropDownInput.tsx
  src/components/common/input/TextInput.tsx
  src/components/common/navbar/navGoal/NavGoal.tsx
  src/components/todoCalendar/ConfirmModal.tsx
  src/components/todoCalendar/CreateTodo.tsx
  src/components/todoCalendar/TodoCalendar.tsx
  src/components/todoCalendar/TodoList.tsx
  src/components/todoCalendar/TodoListItem.tsx
  src/components/todoCalendar/TodoModal.tsx
  src/styles/globals.css
Labels: ✨ Feature

#22 [CAN-36/style] 캘린더 디자인 적용
  src/components/todoCalendar/Calendar.tsx
  src/components/todoCalendar/CalendarBody.tsx
  src/components/todoCalendar/CalendarHeader.tsx
  src/components/todoCalendar/TodoBasket.tsx
  src/components/todoCalendar/TodoCalendar.tsx
  src/components/todoCalendar/TodoList.tsx
  src/components/todoCalendar/TodoListItem.tsx
  src/presets/colors.ts
  src/presets/fontSize.ts
  src/styles/calendar.css
  src/styles/globals.css
  src/types/todos.d.ts
Labels: 🌈Style

#25 [CAN-42/feat] navbar API 연동
  package.json
  pnpm-lock.yaml
  src/app/(member)/layout.tsx
  src/app/(member)/page.tsx
  src/app/api/goals/route.ts
  src/app/layout.tsx
  src/auth.ts
  src/components/common/ClientProvider.tsx
  src/components/common/navbar/NavUserProfile.tsx
  src/components/common/navbar/Navbar.tsx
  src/components/common/navbar/navGoal/NavGoal.tsx
  src/components/common/navbar/navGoal/NavGoalItem.tsx
  src/components/common/navbar/navGoal/NewGoalItem.tsx
  src/constants/errorMessages.ts
  src/constants/queryKey.ts
  src/hooks/useGoals.ts
  src/services/fetchInstance.ts
  src/types/goals.d.ts
Labels: ✨ Feature, 📬 API

#24 [CAN-37/style] 할 일 목록 디자인 적용
  src/components/common/button/Button.tsx
  src/components/common/todo/CheckTodo.tsx
  src/components/todoCalendar/Calendar.tsx
  src/components/todoCalendar/CalendarBody.tsx
  src/components/todoCalendar/CalendarHeader.tsx
  src/components/todoCalendar/TodoCalendar.tsx
  src/components/todoCalendar/TodoList.tsx
  src/components/todoCalendar/TodoListItem.tsx
  src/styles/calendar.css
Labels: 🌈Style

#27 [CAN-24/feat] 할 일 생성 API 연동
  src/app/api/todos/route.ts
  src/components/common/input/DropDownInput.tsx
  src/components/common/todo/CheckTodo.tsx
  src/components/todoCalendar/CreateTodo.tsx
  src/components/todoCalendar/TodoBasket.tsx
  src/components/todoCalendar/TodoCalendar.tsx
  src/components/todoCalendar/TodoModal.tsx
  src/types/todos.d.ts
Labels: ✨ Feature, 📬 API, 🌈Style

#23 [CAN-35/feat] 목표 상세 페이지 할 일 생성 모달
  .husky/_/pre-commit
  .husky/_/pre-push
  package.json
  pnpm-lock.yaml
  src/app/(member)/goals/[id]/note/page.tsx
  src/app/(member)/goals/[id]/page.tsx
  src/app/(member)/page.tsx
  src/auth.config.ts
  src/components/common/todo/CheckTodo.tsx
  src/components/goalDetail/GoalBasket.tsx
  src/components/goalDetail/GoalDoneList.tsx
  src/components/goalDetail/GoalHeader.tsx
  src/components/goalDetail/GoalListItem.tsx
  src/components/goalDetail/GoalTodoList.tsx
  src/components/goalDetail/GoalTodoModal.tsx
  src/components/note/ConfirmDeleteModal.tsx
  src/components/note/NoteHeader.tsx
  src/components/note/NoteItem.tsx
  src/components/note/NoteList.tsx
  src/components/note/NoteModal.tsx
  src/types/todos.d.ts
Labels: ✨ Feature, 🌈Style

#31 [CAN-23/feat] 할 일 조회 API 연동
  package.json
  pnpm-lock.yaml
  src/app/api/todos/daily/route.ts
  src/app/api/todos/monthly/route.ts
  src/app/api/todos/route.ts
  src/components/common/ClientProvider.tsx
  src/components/common/todo/CheckTodo.tsx
  src/components/todoCalendar/Calendar.tsx
  src/components/todoCalendar/CalendarBody.tsx
  src/components/todoCalendar/CalendarHeader.tsx
  src/components/todoCalendar/CreateTodo.tsx
  src/components/todoCalendar/TodoCalendar.tsx
  src/components/todoCalendar/TodoListItem.tsx
  src/constants/queryKey.ts
  src/hooks/useTodos.ts
  src/types/todos.d.ts
Labels: ✨ Feature, 📬 API

#28 [CAN-46/feat] 대시보드 오늘 할일 리스트, 그래프 API 연동
  src/app/(member)/page.tsx
  src/app/api/goals/route.ts
  src/components/common/navbar/navGoal/NavGoal.tsx
  src/components/common/todo/SimpleTodo.tsx
  src/components/dashboard/todayList/TodayList.tsx
  src/components/dashboard/todayList/TodayListEmpty.tsx
  src/components/dashboard/todayList/TodayListSkeleton.tsx
  src/components/dashboard/todayProgress/TodayGraph.tsx
  src/components/dashboard/todayProgress/TodayProgress.tsx
  src/components/dashboard/todayProgress/TodayProgressError.tsx
  src/components/dashboard/todayProgress/TodayProgressSkeleton.tsx
  src/hooks/useGoals.ts
  src/services/dashboard.ts
  src/services/fetchInstance.ts
Labels: ✨ Feature, 📬 API

#33 [CAN-54/feat] 할 일 삭제 API 연동
  src/app/api/todos/[todoId]/route.ts
  src/components/common/ConfirmModal.tsx
  src/components/common/input/DropDownInput.tsx
  src/components/todoCalendar/ConfirmModal.tsx
  src/components/todoCalendar/CreateTodo.tsx
  src/components/todoCalendar/TodoCalendar.tsx
  src/components/todoCalendar/TodoList.tsx
  src/components/todoCalendar/TodoListItem.tsx
  src/components/todoCalendar/TodoModal.tsx
  src/hooks/useTodos.ts
  src/services/todo.ts
Labels: ✨ Feature, 📬 API
